// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiJ0ISnPMxLFGddnlb_cwv84Nl5JKy3UI',
    appId: '1:830202034651:web:42d483eefa431a7c4fcffe',
    messagingSenderId: '830202034651',
    projectId: 'risk-resq',
    authDomain: 'risk-resq.firebaseapp.com',
    storageBucket: 'risk-resq.appspot.com',
    measurementId: 'G-ZNBKTDR4M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxWyq80WeECCJ8ygpghS1p2qlN9Dvto7k',
    appId: '1:830202034651:android:721e8bfe40d8d1fa4fcffe',
    messagingSenderId: '830202034651',
    projectId: 'risk-resq',
    storageBucket: 'risk-resq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk7RxtaoWUHG7MyIINMJchESYo-9H4qIA',
    appId: '1:830202034651:ios:74f02ea5d519b7c54fcffe',
    messagingSenderId: '830202034651',
    projectId: 'risk-resq',
    storageBucket: 'risk-resq.appspot.com',
    iosClientId: '830202034651-7c9rpq26aehi0tqqsn41lt8h1ru69jks.apps.googleusercontent.com',
    iosBundleId: 'com.disastermanagement.riskResq',
  );
}
